<?php
    $numeros = ['1 Uno',
    '2 Dos',
    '3 Tres',
    '4 Cuatro',
    '5 Cinco',
    '6 Seis',
    ' 7 Siete',
    '8 Ocho',
    '9 Nueve',
    '10 Diez',
    '11 Once',
    '12 Doce',
    '13 Trece',
    '14 Catorce',
    '15 Quince',
    '16 Dieciseis',
    '17 Diecisiete',
    '18 Dieciocho',
    '19 Diecinueve',
    '20 Veinte',
    '21 Veintiuno',
    '22 Veintidos',
    '23 Veintitres',
    '24 Veinticuatro',
    '25 Veinticinco',
    '26 Veintiseis',
    '27 Veintisiete',
    '28 Veintiocho',
    '29 Veintinueve',
    '30 Treinta',
    '31 Treinta Y Uno',
    '32 Treinta Y Dos',
    '33 Treinta Y Tres',
    '34 Treinta Y Cuatro',
    '35 Treinta Y Cinco',
    '36 Treinta Y Seis',
    '37 Treinta Y Siete',
    '38 Treinta Y Ocho',
    '39 Treinta Y Nueve',
    '40 Cuarenta',
    '41 Cuarenta Y Uno',
    '42 Cuarenta Y Dos',
    '43 Cuarenta Y Tres',
    '44 Cuarenta Y Cuatro',
    '45 Cuarenta Y Cinco',
    '46 Cuarenta Y Seis',
    '47 Cuarenta Y Siete',
    '48 Cuarenta Y Ocho',
    '49 Cuarenta Y Nueve',
    '50 Cincuenta',
    '51 Cincuenta Y Uno',
    '52 Cincuenta Y Dos',
    '53 Cincuenta Y Tres',
    '54 Cincuenta Y Cuatro',
    '55 Cincuenta Y Cinco',
    '56 Cincuenta Y Seis',
    '57 Cincuenta Y Siete',
    '58 Cincuenta Y Ocho',
    '59 Cincuenta Y Nueve',
    '60 Sesenta',
    '61 Sesenta Y Uno',
    '62 Sesenta Y Dos',
    '63 Sesenta Y Tres',
    '64 Sesenta Y Cuatro',
    '65 Sesenta Y Cinco',
    '66 Sesenta Y Seis',
    '67 Sesenta Y Siete',
    '68 Sesenta Y Ocho',
    '69 Sesenta Y Nueve',
    '70 Setenta',
    '71 Setenta Y Uno',
    '72 Setenta Y Dos',
    '73 Setenta Y Tres',
    '74 Setenta Y Cuatro',
    '75 Setenta Y Cinco',
    '76 Setenta Y Seis',
    '77 Setenta Y Siete',
    '78 Setenta Y Ocho',
    '79 Setenta Y Nueve',
    '80 Ochenta',
    '81 Ochenta Y Uno',
    '82 Ochenta Y Dos',
    '83 Ochenta Y Tres',
    '84 Ochenta Y Cuatro',
    '85 Ochenta Y Cinco',
    '86 Ochenta Y Seis',
    '87 Ochenta Y Siete',
    '88 Ochenta Y Ocho',
    '89 Ochenta Y Nueve',
    '90 Noventa',
    '91 Noventa Y Uno',
    '92 Noventa Y Dos',
    '93 Noventa Y Tres',
    '94 Noventa Y Cuatro',
    '95 Noventa Y Cinco',
    '96 Noventa Y Seis',
    '97 Noventa Y Siete',
    '98 Noventa Y Ocho',
    '99 Noventa Y Nueve',
    '100 Cien',
    '101 Ciento Uno',
    '102 Ciento Dos',
    '103 Ciento Tres',
    '104 Ciento Cuatro',
    '105 Ciento Cinco',
    '106 Ciento Seis',
    '107 Ciento Siete',
    '108 Ciento Ocho',
    '109 Ciento Nueve',
    '110 Ciento Diez',
    '111 Ciento Once',
    '112 Ciento Doce',
    '113 Ciento Trece',
    '114 Ciento Catorce',
    '115 Ciento Quince',
    '116 Ciento Dieciséis',
    '117 Ciento Diecisiete',
    '118 Ciento Dieciocho',
    '119 Ciento Diecinueve',
    '120 Ciento Veinte',
    '121 Ciento Veintiuno',
    '122 Ciento Veintidós',
    '123 Ciento Veintitrés',
    '124 Ciento Veinticuatro',
    '125 Ciento Veinticinco',
    '126 Ciento Veintiséis',
    '127 Ciento Veintisiete',
    '128 Ciento Veintiocho',
    '129 Ciento Veintinueve',
    '130 Ciento Treinta',
    '131 Ciento Treinta Y Uno',
    '132 Ciento Treinta Y Dos',
    '133 Ciento Treinta Y Tres',
    '134 Ciento Treinta Y Cuatro',
    '135 Ciento Treinta Y Cinco',
    '136 Ciento Treinta Y Seis',
    '137 Ciento Treinta Y Siete',
    '138 Ciento Treinta Y Ocho',
    '139 Ciento Treinta Y Nueve',
    '140 Ciento Cuarenta',
    '141 Ciento Cuarenta Y Uno',
    '142 Ciento Cuarenta Y Dos',
    '143 Ciento Cuarenta Y Tres',
    '144 Ciento Cuarenta Y Cuatro',
    '145 Ciento Cuarenta Y Cinco',
    '146 Ciento Cuarenta Y Seis',
    '147 Ciento Cuarenta Y Siete',
    '148 Ciento Cuarenta Y Ocho',
    '149 Ciento Cuarenta Y Nueve',
    '150 Ciento Cincuenta',
    '151 Ciento Cincuenta Y Uno',
    '152 Ciento Cincuenta Y Dos',
    '153 Ciento Cincuenta Y Tres',
    '154 Ciento Cincuenta Y Cuatro',
    '155 Ciento Cincuenta Y Cinco',
    '156 Ciento Cincuenta Y Seis',
    '157 Ciento Cincuenta Y Siete',
    '158 Ciento Cincuenta Y Ocho',
    '159 Ciento Cincuenta Y Nueve',
    '160 Ciento Sesenta',
    '161 Ciento Sesenta Y Uno',
    '162 Ciento Sesenta Y Dos',
    '163 Ciento Sesenta Y Tres',
    '164 Ciento Sesenta Y Cuatro',
    '165 Ciento Sesenta Y Cinco',
    '166 Ciento Sesenta Y Seis',
    '167 Ciento Sesenta Y Siete',
    '168 Ciento Sesenta Y Ocho',
    '169 Ciento Sesenta Y Nueve',
    '170 Ciento Setenta',
    '171 Ciento Setenta Y Uno',
    '172 Ciento Setenta Y Dos',
    '173 Ciento Setenta Y Tres',
    '174 Ciento Setenta Y Cuatro',
    '175 Ciento Setenta Y Cinco',
    '176 Ciento Setenta Y Seis',
    '177 Ciento Setenta Y Siete',
    '178 Ciento Setenta Y Ocho',
    '179 Ciento Setenta Y Nueve',
    '180 Ciento Ochenta',
    '181 Ciento Ochenta Y Uno',
    '182 Ciento Ochenta Y Dos',
    '183 Ciento Ochenta Y Tres',
    '184 Ciento Ochenta Y Cuatro',
    '185 Ciento Ochenta Y Cinco',
    '186 Ciento Ochenta Y Seis',
    '187 Ciento Ochenta Y Siete',
    '188 Ciento Ochenta Y Ocho',
    '189 Ciento Ochenta Y Nueve',
    '190 Ciento Noventa',
    '191 Ciento Noventa Y Uno',
    '192 Ciento Noventa Y Dos',
    '193 Ciento Noventa Y Tres',
    '194 Ciento Noventa Y Cuatro',
    '195 Ciento Noventa Y Cinco',
    '196 Ciento Noventa Y Seis',
    '197 Ciento Noventa Y Siete',
    '198 Ciento Noventa Y Ocho',
    '199 Ciento Noventa Y Nueve',
    '200 Doscientos',
    '201 Doscientos Uno',
    '202 Doscientos Dos',
    '203 Doscientos Tres',
    '204 Doscientos Cuatro',
    '205 Doscientos Cinco',
    '206 Doscientos Seis',
    '207 Doscientos Siete',
    '208 Doscientos Ocho',
    '209 Doscientos Nueve',
    '210 Doscientos Diez',
    '211 Doscientos Once',
    '212 Doscientos Doce',
    '213 Doscientos Trece',
    '214 Doscientos Catorce',
    '215 Doscientos Quince',
    '216 Doscientos Dieciséis',
    '217 Doscientos Diecisiete',
    '218 Doscientos Dieciocho',
    '219 Doscientos Diecinueve',
    '220 Doscientos Veinte',
    '221 Doscientos Veintiuno',
    '222 Doscientos Veintidós',
    '223 Doscientos Veintitrés',
    '224 Doscientos Veinticuatro',
    '225 Doscientos Veinticinco',
    '226 Doscientos Veintiséis',
    '227 Doscientos Veintisiete',
    '228 Doscientos Veintiocho',
    '229 Doscientos Veintinueve',
    '230 Doscientos Treinta',
    '231 Doscientos Treinta Y Uno',
    '232 Doscientos Treinta Y Dos',
    '233 Doscientos Treinta Y Tres',
    '234 Doscientos Treinta Y Cuatro',
    '235 Doscientos Treinta Y Cinco',
    '236 Doscientos Treinta Y Seis',
    '237 Doscientos Treinta Y Siete',
    '238 Doscientos Treinta Y Ocho',
    '239 Doscientos Treinta Y Nueve',
    '240 Doscientos Cuarenta',
    '241 Doscientos Cuarenta Y Uno',
    '242 Doscientos Cuarenta Y Dos',
    '243 Doscientos Cuarenta Y Tres',
    '244 Doscientos Cuarenta Y Cuatro',
    '245 Doscientos Cuarenta Y Cinco',
    '246 Doscientos Cuarenta Y Seis',
    '247 Doscientos Cuarenta Y Siete',
    '248 Doscientos Cuarenta Y Ocho',
    '249 Doscientos Cuarenta Y Nueve',
    '250 Doscientos Cincuenta',
    '251 Doscientos Cincuenta Y Uno',
    '252 Doscientos Cincuenta Y Dos',
    '253 Doscientos Cincuenta Y Tres',
    '254 Doscientos Cincuenta Y Cuatro',
    '255 Doscientos Cincuenta Y Cinco',
    '256 Doscientos Cincuenta Y Seis',
    '257 Doscientos Cincuenta Y Siete',
    '258 Doscientos Cincuenta Y Ocho',
    '259 Doscientos Cincuenta Y Nueve',
    '260 Doscientos Sesenta',
    '261 Doscientos Sesenta Y Uno',
    '262 Doscientos Sesenta Y Dos',
    '263 Doscientos Sesenta Y Tres',
    '264 Doscientos Sesenta Y Cuatro',
    '265 Doscientos Sesenta Y Cinco',
    '266 Doscientos Sesenta Y Seis',
    '267 Doscientos Sesenta Y Siete',
    '268 Doscientos Sesenta Y Ocho',
    '269 Doscientos Sesenta Y Nueve',
    '270 Doscientos Setenta',
    '271 Doscientos Setenta Y Uno',
    '272 Doscientos Setenta Y Dos',
    '273 Doscientos Setenta Y Tres',
    '274 Doscientos Setenta Y Cuatro',
    '275 Doscientos Setenta Y Cinco',
    '276 Doscientos Setenta Y Seis',
    '277 Doscientos Setenta Y Siete',
    '278 Doscientos Setenta Y Ocho',
    '279 Doscientos Setenta Y Nueve',
    '280 Doscientos Ochenta',
    '281 Doscientos Ochenta Y Uno',
    '282 Doscientos Ochenta Y Dos',
    '283 Doscientos Ochenta Y Tres',
    '284 Doscientos Ochenta Y Cuatro',
    '285 Doscientos Ochenta Y Cinco',
    '286 Doscientos Ochenta Y Seis',
    '287 Doscientos Ochenta Y Siete',
    '288 Doscientos Ochenta Y Ocho',
    '289 Doscientos Ochenta Y Nueve',
    '290 Doscientos Noventa',
    '291 Doscientos Noventa Y Uno',
    '292 Doscientos Noventa Y Dos',
    '293 Doscientos Noventa Y Tres',
    '294 Doscientos Noventa Y Cuatro',
    '295 Doscientos Noventa Y Cinco',
    '296 Doscientos Noventa Y Seis',
    '297 Doscientos Noventa Y Siete',
    '298 Doscientos Noventa Y Ocho',
    '299 Doscientos Noventa Y Nueve',
    '300 Trescientos',
    '301 Trescientos Uno',
    '302 Trescientos Dos',
    '303 Trescientos Tres',
    '304 Trescientos Cuatro',
    '305 Trescientos Cinco',
    '306 Trescientos Seis',
    '307 Trescientos Siete',
    '308 Trescientos Ocho',
    '309 Trescientos Nueve',
    '310 Trescientos Diez',
    '311 Trescientos Once',
    '312 Trescientos Doce',
    '313 Trescientos Trece',
    '314 Trescientos Catorce',
    '315 Trescientos Quince',
    '316 Trescientos Dieciséis',
    '317 Trescientos Diecisiete',
    '318 Trescientos Dieciocho',
    '319 Trescientos Diecinueve',
    '320 Trescientos Veinte',
    '321 Trescientos Veintiuno',
    '322 Trescientos Veintidós',
    '323 Trescientos Veintitrés',
    '324 Trescientos Veinticuatro',
    '325 Trescientos Veinticinco',
    '326 Trescientos Veintiséis',
    '327 Trescientos Veintisiete',
    '328 Trescientos Veintiocho',
    '329 Trescientos Veintinueve',
    '330 Trescientos Treinta',
    '331 Trescientos Treinta Y Uno',
    '332 Trescientos Treinta Y Dos',
    '333 Trescientos Treinta Y Tres',
    '334 Trescientos Treinta Y Cuatro',
    '335 Trescientos Treinta Y Cinco',
    '336 Trescientos Treinta Y Seis',
    '337 Trescientos Treinta Y Siete',
    '338 Trescientos Treinta Y Ocho',
    '339 Trescientos Treinta Y Nueve',
    '340 Trescientos Cuarenta',
    '341 Trescientos Cuarenta Y Uno',
    '342 Trescientos Cuarenta Y Dos',
    '343 Trescientos Cuarenta Y Tres',
    '344 Trescientos Cuarenta Y Cuatro',
    '345 Trescientos Cuarenta Y Cinco',
    '346 Trescientos Cuarenta Y Seis',
    '347 Trescientos Cuarenta Y Siete',
    '348 Trescientos Cuarenta Y Ocho',
    '349 Trescientos Cuarenta Y Nueve',
    '350 Trescientos Cincuenta',
    '351 Trescientos Cincuenta Y Uno',
    '352 Trescientos Cincuenta Y Dos',
    '353 Trescientos Cincuenta Y Tres',
    '354 Trescientos Cincuenta Y Cuatro',
    '355 Trescientos Cincuenta Y Cinco',
    '356 Trescientos Cincuenta Y Seis',
    '357 Trescientos Cincuenta Y Siete',
    '358 Trescientos Cincuenta Y Ocho',
    '359 Trescientos Cincuenta Y Nueve',
    '360 Trescientos Sesenta',
    '361 Trescientos Sesenta Y Uno',
    '362 Trescientos Sesenta Y Dos',
    '363 Trescientos Sesenta Y Tres',
    '364 Trescientos Sesenta Y Cuatro',
    '365 Trescientos Sesenta Y Cinco',
    '366 Trescientos Sesenta Y Seis',
    '367 Trescientos Sesenta Y Siete',
    '368 Trescientos Sesenta Y Ocho',
    '369 Trescientos Sesenta Y Nueve',
    '370 Trescientos Setenta',
    '371 Trescientos Setenta Y Uno',
    '372 Trescientos Setenta Y Dos',
    '373 Trescientos Setenta Y Tres',
    '374 Trescientos Setenta Y Cuatro',
    '375 Trescientos Setenta Y Cinco',
    '376 Trescientos Setenta Y Seis',
    '377 Trescientos Setenta Y Siete',
    '378 Trescientos Setenta Y Ocho',
    '379 Trescientos Setenta Y Nueve',
    '380 Trescientos Ochenta',
    '381 Trescientos Ochenta Y Uno',
    '382 Trescientos Ochenta Y Dos',
    '383 Trescientos Ochenta Y Tres',
    '384 Trescientos Ochenta Y Cuatro',
    '385 Trescientos Ochenta Y Cinco',
    '386 Trescientos Ochenta Y Seis',
    '387 Trescientos Ochenta Y Siete',
    '388 Trescientos Ochenta Y Ocho',
    '389 Trescientos Ochenta Y Nueve',
    '390 Trescientos Noventa',
    '391 Trescientos Noventa Y Uno',
    '392 Trescientos Noventa Y Dos',
    '393 Trescientos Noventa Y Tres',
    '394 Trescientos Noventa Y Cuatro',
    '395 Trescientos Noventa Y Cinco',
    '396 Trescientos Noventa Y Seis',
    '397 Trescientos Noventa Y Siete',
    '398 Trescientos Noventa Y Ocho',
    '399 Trescientos Noventa Y Nueve',
    '400 Cuatrocientos',
    '401 Cuatrocientos Uno',
    '402 Cuatrocientos Dos',
    '403 Cuatrocientos Tres',
    '404 Cuatrocientos Cuatro',
    '405 Cuatrocientos Cinco',
    '406 Cuatrocientos Seis',
    '407 Cuatrocientos Siete',
    '408 Cuatrocientos Ocho',
    '409 Cuatrocientos Nueve',
    '410 Cuatrocientos Diez',
    '411 Cuatrocientos Once',
    '412 Cuatrocientos Doce',
    '413 Cuatrocientos Trece',
    '414 Cuatrocientos Catorce',
    '415 Cuatrocientos Quince',
    '416 Cuatrocientos Dieciséis',
    '417 Cuatrocientos Diecisiete',
    '418 Cuatrocientos Dieciocho',
    '419 Cuatrocientos Diecinueve',
    '420 Cuatrocientos Veinte',
    '421 Cuatrocientos Veintiuno',
    '422 Cuatrocientos Veintidós',
    '423 Cuatrocientos Veintitrés',
    '424 Cuatrocientos Veinticuatro',
    '425 Cuatrocientos Veinticinco',
    '426 Cuatrocientos Veintiséis',
    '427 Cuatrocientos Veintisiete',
    '428 Cuatrocientos Veintiocho',
    '429 Cuatrocientos Veintinueve',
    '430 Cuatrocientos Treinta',
    '431 Cuatrocientos Treinta Y Uno',
    '432 Cuatrocientos Treinta Y Dos',
    '433 Cuatrocientos Treinta Y Tres',
    '434 Cuatrocientos Treinta Y Cuatro',
    '435 Cuatrocientos Treinta Y Cinco',
    '436 Cuatrocientos Treinta Y Seis',
    '437 Cuatrocientos Treinta Y Siete',
    '438 Cuatrocientos Treinta Y Ocho',
    '439 Cuatrocientos Treinta Y Nueve',
    '440 Cuatrocientos Cuarenta',
    '441 Cuatrocientos Cuarenta Y Uno',
    '442 Cuatrocientos Cuarenta Y Dos',
    '443 Cuatrocientos Cuarenta Y Tres',
    '444 Cuatrocientos Cuarenta Y Cuatro',
    '445 Cuatrocientos Cuarenta Y Cinco',
    '446 Cuatrocientos Cuarenta Y Seis',
    '447 Cuatrocientos Cuarenta Y Siete',
    '448 Cuatrocientos Cuarenta Y Ocho',
    '449 Cuatrocientos Cuarenta Y Nueve',
    '450 Cuatrocientos Cincuenta',
    '451 Cuatrocientos Cincuenta Y Uno',
    '452 Cuatrocientos Cincuenta Y Dos',
    '453 Cuatrocientos Cincuenta Y Tres',
    '454 Cuatrocientos Cincuenta Y Cuatro',
    '455 Cuatrocientos Cincuenta Y Cinco',
    '456 Cuatrocientos Cincuenta Y Seis',
    '457 Cuatrocientos Cincuenta Y Siete',
    '458 Cuatrocientos Cincuenta Y Ocho',
    '459 Cuatrocientos Cincuenta Y Nueve',
    '460 Cuatrocientos Sesenta',
    '461 Cuatrocientos Sesenta Y Uno',
    '462 Cuatrocientos Sesenta Y Dos',
    '463 Cuatrocientos Sesenta Y Tres',
    '464 Cuatrocientos Sesenta Y Cuatro',
    '465 Cuatrocientos Sesenta Y Cinco',
    '466 Cuatrocientos Sesenta Y Seis',
    '467 Cuatrocientos Sesenta Y Siete',
    '468 Cuatrocientos Sesenta Y Ocho',
    '469 Cuatrocientos Sesenta Y Nueve',
    '470 Cuatrocientos Setenta',
    '471 Cuatrocientos Setenta Y Uno',
    '472 Cuatrocientos Setenta Y Dos',
    '473 Cuatrocientos Setenta Y Tres',
    '474 Cuatrocientos Setenta Y Cuatro',
    '475 Cuatrocientos Setenta Y Cinco',
    '476 Cuatrocientos Setenta Y Seis',
    '477 Cuatrocientos Setenta Y Siete',
    '478 Cuatrocientos Setenta Y Ocho',
    '479 Cuatrocientos Setenta Y Nueve',
    '480 Cuatrocientos Ochenta',
    '481 Cuatrocientos Ochenta Y Uno',
    '482 Cuatrocientos Ochenta Y Dos',
    '483 Cuatrocientos Ochenta Y Tres',
    '484 Cuatrocientos Ochenta Y Cuatro',
    '485 Cuatrocientos Ochenta Y Cinco',
    '486 Cuatrocientos Ochenta Y Seis',
    '487 Cuatrocientos Ochenta Y Siete',
    '488 Cuatrocientos Ochenta Y Ocho',
    '489 Cuatrocientos Ochenta Y Nueve',
    '490 Cuatrocientos Noventa',
    '491 Cuatrocientos Noventa Y Uno',
    '492 Cuatrocientos Noventa Y Dos',
    '493 Cuatrocientos Noventa Y Tres',
    '494 Cuatrocientos Noventa Y Cuatro',
    '495 Cuatrocientos Noventa Y Cinco',
    '496 Cuatrocientos Noventa Y Seis',
    '497 Cuatrocientos Noventa Y Siete',
    '498 Cuatrocientos Noventa Y Ocho',
    '499 Cuatrocientos Noventa Y Nueve',
    '500 Quinientos',
    '501 Quinientos Uno',
    '502 Quinientos Dos',
    '503 Quinientos Tres',
    '504 Quinientos Cuatro',
    '505 Quinientos Cinco',
    '506 Quinientos Seis',
    '507 Quinientos Siete',
    '508 Quinientos Ocho',
    '509 Quinientos Nueve',
    '510 Quinientos Diez',
    '511 Quinientos Once',
    '512 Quinientos Doce',
    '513 Quinientos Trece',
    '514 Quinientos Catorce',
    '515 Quinientos Quince',
    '516 Quinientos Dieciséis',
    '517 Quinientos Diecisiete',
    '518 Quinientos Dieciocho',
    '519 Quinientos Diecinueve',
    '520 Quinientos Veinte',
    '521 Quinientos Veintiuno',
    '522 Quinientos Veintidós',
    '523 Quinientos Veintitrés',
    '524 Quinientos Veinticuatro',
    '525 Quinientos Veinticinco',
    '526 Quinientos Veintiséis',
    '527 Quinientos Veintisiete',
    '528 Quinientos Veintiocho',
    '529 Quinientos Veintinueve',
    '530 Quinientos Treinta',
    '531 Quinientos Treinta Y Uno',
    '532 Quinientos Treinta Y Dos',
    '533 Quinientos Treinta Y Tres',
    '534 Quinientos Treinta Y Cuatro',
    '535 Quinientos Treinta Y Cinco',
    '536 Quinientos Treinta Y Seis',
    '537 Quinientos Treinta Y Siete',
    '538 Quinientos Treinta Y Ocho',
    '539 Quinientos Treinta Y Nueve',
    '540 Quinientos Cuarenta',
    '541 Quinientos Cuarenta Y Uno',
    '542 Quinientos Cuarenta Y Dos',
    '543 Quinientos Cuarenta Y Tres',
    '544 Quinientos Cuarenta Y Cuatro',
    '545 Quinientos Cuarenta Y Cinco',
    '546 Quinientos Cuarenta Y Seis',
    '547 Quinientos Cuarenta Y Siete',
    '548 Quinientos Cuarenta Y Ocho',
    '549 Quinientos Cuarenta Y Nueve',
    '550 Quinientos Cincuenta',
    '551 Quinientos Cincuenta Y Uno',
    '552 Quinientos Cincuenta Y Dos',
    '553 Quinientos Cincuenta Y Tres',
    '554 Quinientos Cincuenta Y Cuatro',
    '555 Quinientos Cincuenta Y Cinco',
    '556 Quinientos Cincuenta Y Seis',
    '557 Quinientos Cincuenta Y Siete',
    '558 Quinientos Cincuenta Y Ocho',
    '559 Quinientos Cincuenta Y Nueve',
    '560 Quinientos Sesenta',
    '561 Quinientos Sesenta Y Uno',
    '562 Quinientos Sesenta Y Dos',
    '563 Quinientos Sesenta Y Tres',
    '564 Quinientos Sesenta Y Cuatro',
    '565 Quinientos Sesenta Y Cinco',
    '566 Quinientos Sesenta Y Seis',
    '567 Quinientos Sesenta Y Siete',
    '568 Quinientos Sesenta Y Ocho',
    '569 Quinientos Sesenta Y Nueve',
    '570 Quinientos Setenta',
    '571 Quinientos Setenta Y Uno',
    '572 Quinientos Setenta Y Dos',
    '573 Quinientos Setenta Y Tres',
    '574 Quinientos Setenta Y Cuatro',
    '575 Quinientos Setenta Y Cinco',
    '576 Quinientos Setenta Y Seis',
    '577 Quinientos Setenta Y Siete',
    '578 Quinientos Setenta Y Ocho',
    '579 Quinientos Setenta Y Nueve',
    '580 Quinientos Ochenta',
    '581 Quinientos Ochenta Y Uno',
    '582 Quinientos Ochenta Y Dos',
    '583 Quinientos Ochenta Y Tres',
    '584 Quinientos Ochenta Y Cuatro',
    '585 Quinientos Ochenta Y Cinco',
    '586 Quinientos Ochenta Y Seis',
    '587 Quinientos Ochenta Y Siete',
    '588 Quinientos Ochenta Y Ocho',
    '589 Quinientos Ochenta Y Nueve',
    '590 Quinientos Noventa',
    '591 Quinientos Noventa Y Uno',
    '592 Quinientos Noventa Y Dos',
    '593 Quinientos Noventa Y Tres',
    '594 Quinientos Noventa Y Cuatro',
    '595 Quinientos Noventa Y Cinco',
    '596 Quinientos Noventa Y Seis',
    '597 Quinientos Noventa Y Siete',
    '598 Quinientos Noventa Y Ocho',
    '599 Quinientos Noventa Y Nueve',
    '600 Seiscientos',
    '601 Seiscientos Uno',
    '602 Seiscientos Dos',
    '603 Seiscientos Tres',
    '604 Seiscientos Cuatro',
    '605 Seiscientos Cinco',
    '606 Seiscientos Seis',
    '607 Seiscientos Siete',
    '608 Seiscientos Ocho',
    '609 Seiscientos Nueve',
    '610 Seiscientos Diez',
    '611 Seiscientos Once',
    '612 Seiscientos Doce',
    '613 Seiscientos Trece',
    '614 Seiscientos Catorce',
    '615 Seiscientos Quince',
    '616 Seiscientos Dieciséis',
    '617 Seiscientos Diecisiete',
    '618 Seiscientos Dieciocho',
    '619 Seiscientos Diecinueve',
    '620 Seiscientos Veinte',
    '621 Seiscientos Veintiuno',
    '622 Seiscientos Veintidós',
    '623 Seiscientos Veintitrés',
    '624 Seiscientos Veinticuatro',
    '625 Seiscientos Veinticinco',
    '626 Seiscientos Veintiséis',
    '627 Seiscientos Veintisiete',
    '628 Seiscientos Veintiocho',
    '629 Seiscientos Veintinueve',
    '630 Seiscientos Treinta',
    '631 Seiscientos Treinta Y Uno',
    '632 Seiscientos Treinta Y Dos',
    '633 Seiscientos Treinta Y Tres',
    '634 Seiscientos Treinta Y Cuatro',
    '635 Seiscientos Treinta Y Cinco',
    '636 Seiscientos Treinta Y Seis',
    '637 Seiscientos Treinta Y Siete',
    '638 Seiscientos Treinta Y Ocho',
    '639 Seiscientos Treinta Y Nueve',
    '640 Seiscientos Cuarenta',
    '641 Seiscientos Cuarenta Y Uno',
    '642 Seiscientos Cuarenta Y Dos',
    '643 Seiscientos Cuarenta Y Tres',
    '644 Seiscientos Cuarenta Y Cuatro',
    '645 Seiscientos Cuarenta Y Cinco',
    '646 Seiscientos Cuarenta Y Seis',
    '647 Seiscientos Cuarenta Y Siete',
    '648 Seiscientos Cuarenta Y Ocho',
    '649 Seiscientos Cuarenta Y Nueve',
    '650 Seiscientos Cincuenta',
    '651 Seiscientos Cincuenta Y Uno',
    '652 Seiscientos Cincuenta Y Dos',
    '653 Seiscientos Cincuenta Y Tres',
    '654 Seiscientos Cincuenta Y Cuatro',
    '655 Seiscientos Cincuenta Y Cinco',
    '656 Seiscientos Cincuenta Y Seis',
    '657 Seiscientos Cincuenta Y Siete',
    '658 Seiscientos Cincuenta Y Ocho',
    '659 Seiscientos Cincuenta Y Nueve',
    '660 Seiscientos Sesenta',
    '661 Seiscientos Sesenta Y Uno',
    '662 Seiscientos Sesenta Y Dos',
    '663 Seiscientos Sesenta Y Tres',
    '664 Seiscientos Sesenta Y Cuatro',
    '665 Seiscientos Sesenta Y Cinco',
    '666 Seiscientos Sesenta Y Seis',
    '667 Seiscientos Sesenta Y Siete',
    '668 Seiscientos Sesenta Y Ocho',
    '669 Seiscientos Sesenta Y Nueve',
    '670 Seiscientos Setenta',
    '671 Seiscientos Setenta Y Uno',
    '672 Seiscientos Setenta Y Dos',
    '673 Seiscientos Setenta Y Tres',
    '674 Seiscientos Setenta Y Cuatro',
    '675 Seiscientos Setenta Y Cinco',
    '676 Seiscientos Setenta Y Seis',
    '677 Seiscientos Setenta Y Siete',
    '678 Seiscientos Setenta Y Ocho',
    '679 Seiscientos Setenta Y Nueve',
    '680 Seiscientos Ochenta',
    '681 Seiscientos Ochenta Y Uno',
    '682 Seiscientos Ochenta Y Dos',
    '683 Seiscientos Ochenta Y Tres',
    '684 Seiscientos Ochenta Y Cuatro',
    '685 Seiscientos Ochenta Y Cinco',
    '686 Seiscientos Ochenta Y Seis',
    '687 Seiscientos Ochenta Y Siete',
    '688 Seiscientos Ochenta Y Ocho',
    '689 Seiscientos Ochenta Y Nueve',
    '690 Seiscientos Noventa',
    '691 Seiscientos Noventa Y Uno',
    '692 Seiscientos Noventa Y Dos',
    '693 Seiscientos Noventa Y Tres',
    '694 Seiscientos Noventa Y Cuatro',
    '695 Seiscientos Noventa Y Cinco',
    '696 Seiscientos Noventa Y Seis',
    '697 Seiscientos Noventa Y Siete',
    '698 Seiscientos Noventa Y Ocho',
    '699 Seiscientos Noventa Y Nueve',
    '700 Setecientos',
    '701 Setecientos Uno',
    '702 Setecientos Dos',
    '703 Setecientos Tres',
    '704 Setecientos Cuatro',
    '705 Setecientos Cinco',
    '706 Setecientos Seis',
    '707 Setecientos Siete',
    '708 Setecientos Ocho',
    '709 Setecientos Nueve',
    '710 Setecientos Diez',
    '711 Setecientos Once',
    '712 Setecientos Doce',
    '713 Setecientos Trece',
    '714 Setecientos Catorce',
    '715 Setecientos Quince',
    '716 Setecientos Dieciséis',
    '717 Setecientos Diecisiete',
    '718 Setecientos Dieciocho',
    '719 Setecientos Diecinueve',
    '720 Setecientos Veinte',
    '721 Setecientos Veintiuno',
    '722 Setecientos Veintidós',
    '723 Setecientos Veintitrés',
    '724 Setecientos Veinticuatro',
    '725 Setecientos Veinticinco',
    '726 Setecientos Veintiséis',
    '727 Setecientos Veintisiete',
    '728 Setecientos Veintiocho',
    '729 Setecientos Veintinueve',
    '730 Setecientos Treinta',
    '731 Setecientos Treinta Y Uno',
    '732 Setecientos Treinta Y Dos',
    '733 Setecientos Treinta Y Tres',
    '734 Setecientos Treinta Y Cuatro',
    '735 Setecientos Treinta Y Cinco',
    '736 Setecientos Treinta Y Seis',
    '737 Setecientos Treinta Y Siete',
    '738 Setecientos Treinta Y Ocho',
    '739 Setecientos Treinta Y Nueve',
    '740 Setecientos Cuarenta',
    '741 Setecientos Cuarenta Y Uno',
    '742 Setecientos Cuarenta Y Dos',
    '743 Setecientos Cuarenta Y Tres',
    '744 Setecientos Cuarenta Y Cuatro',
    '745 Setecientos Cuarenta Y Cinco',
    '746 Setecientos Cuarenta Y Seis',
    '747 Setecientos Cuarenta Y Siete',
    '748 Setecientos Cuarenta Y Ocho',
    '749 Setecientos Cuarenta Y Nueve',
    '750 Setecientos Cincuenta',
    '751 Setecientos Cincuenta Y Uno',
    '752 Setecientos Cincuenta Y Dos',
    '753 Setecientos Cincuenta Y Tres',
    '754 Setecientos Cincuenta Y Cuatro',
    '755 Setecientos Cincuenta Y Cinco',
    '756 Setecientos Cincuenta Y Seis',
    '757 Setecientos Cincuenta Y Siete',
    '758 Setecientos Cincuenta Y Ocho',
    '759 Setecientos Cincuenta Y Nueve',
    '760 Setecientos Sesenta',
    '761 Setecientos Sesenta Y Uno',
    '762 Setecientos Sesenta Y Dos',
    '763 Setecientos Sesenta Y Tres',
    '764 Setecientos Sesenta Y Cuatro',
    '765 Setecientos Sesenta Y Cinco',
    '766 Setecientos Sesenta Y Seis',
    '767 Setecientos Sesenta Y Siete',
    '768 Setecientos Sesenta Y Ocho',
    '769 Setecientos Sesenta Y Nueve',
    '770 Setecientos Setenta',
    '771 Setecientos Setenta Y Uno',
    '772 Setecientos Setenta Y Dos',
    '773 Setecientos Setenta Y Tres',
    '774 Setecientos Setenta Y Cuatro',
    '775 Setecientos Setenta Y Cinco',
    '776 Setecientos Setenta Y Seis',
    '777 Setecientos Setenta Y Siete',
    '778 Setecientos Setenta Y Ocho',
    '779 Setecientos Setenta Y Nueve',
    '780 Setecientos Ochenta',
    '781 Setecientos Ochenta Y Uno',
    '782 Setecientos Ochenta Y Dos',
    '783 Setecientos Ochenta Y Tres',
    '784 Setecientos Ochenta Y Cuatro',
    '785 Setecientos Ochenta Y Cinco',
    '786 Setecientos Ochenta Y Seis',
    '787 Setecientos Ochenta Y Siete',
    '788 Setecientos Ochenta Y Ocho',
    '789 Setecientos Ochenta Y Nueve',
    '790 Setecientos Noventa',
    '791 Setecientos Noventa Y Uno',
    '792 Setecientos Noventa Y Dos',
    '793 Setecientos Noventa Y Tres',
    '794 Setecientos Noventa Y Cuatro',
    '795 Setecientos Noventa Y Cinco',
    '796 Setecientos Noventa Y Seis',
    '797 Setecientos Noventa Y Siete',
    '798 Setecientos Noventa Y Ocho',
    '799 Setecientos Noventa Y Nueve',
    '800 Ochocientos',
    '801 Ochocientos Uno',
    '802 Ochocientos Dos',
    '803 Ochocientos Tres',
    '804 Ochocientos Cuatro',
    '805 Ochocientos Cinco',
    '806 Ochocientos Seis',
    '807 Ochocientos Siete',
    '808 Ochocientos Ocho',
    '809 Ochocientos Nueve',
    '810 Ochocientos Diez',
    '811 Ochocientos Once',
    '812 Ochocientos Doce',
    '813 Ochocientos Trece',
    '814 Ochocientos Catorce',
    '815 Ochocientos Quince',
    '816 Ochocientos Dieciséis',
    '817 Ochocientos Diecisiete',
    '818 Ochocientos Dieciocho',
    '819 Ochocientos Diecinueve',
    '820 Ochocientos Veinte',
    '821 Ochocientos Veintiuno',
    '822 Ochocientos Veintidós',
    '823 Ochocientos Veintitrés',
    '824 Ochocientos Veinticuatro',
    '825 Ochocientos Veinticinco',
    '826 Ochocientos Veintiséis',
    '827 Ochocientos Veintisiete',
    '828 Ochocientos Veintiocho',
    '829 Ochocientos Veintinueve',
    '830 Ochocientos Treinta',
    '831 Ochocientos Treinta Y Uno',
    '832 Ochocientos Treinta Y Dos',
    '833 Ochocientos Treinta Y Tres',
    '834 Ochocientos Treinta Y Cuatro',
    '835 Ochocientos Treinta Y Cinco',
    '836 Ochocientos Treinta Y Seis',
    '837 Ochocientos Treinta Y Siete',
    '838 Ochocientos Treinta Y Ocho',
    '839 Ochocientos Treinta Y Nueve',
    '840 Ochocientos Cuarenta',
    '841 Ochocientos Cuarenta Y Uno',
    '842 Ochocientos Cuarenta Y Dos',
    '843 Ochocientos Cuarenta Y Tres',
    '844 Ochocientos Cuarenta Y Cuatro',
    '845 Ochocientos Cuarenta Y Cinco',
    '846 Ochocientos Cuarenta Y Seis',
    '847 Ochocientos Cuarenta Y Siete',
    '848 Ochocientos Cuarenta Y Ocho',
    '849 Ochocientos Cuarenta Y Nueve',
    '850 Ochocientos Cincuenta',
    '851 Ochocientos Cincuenta Y Uno',
    '852 Ochocientos Cincuenta Y Dos',
    '853 Ochocientos Cincuenta Y Tres',
    '854 Ochocientos Cincuenta Y Cuatro',
    '855 Ochocientos Cincuenta Y Cinco',
    '856 Ochocientos Cincuenta Y Seis',
    '857 Ochocientos Cincuenta Y Siete',
    '858 Ochocientos Cincuenta Y Ocho',
    '859 Ochocientos Cincuenta Y Nueve',
    '860 Ochocientos Sesenta',
    '861 Ochocientos Sesenta Y Uno',
    '862 Ochocientos Sesenta Y Dos',
    '863 Ochocientos Sesenta Y Tres',
    '864 Ochocientos Sesenta Y Cuatro',
    '865 Ochocientos Sesenta Y Cinco',
    '866 Ochocientos Sesenta Y Seis',
    '867 Ochocientos Sesenta Y Siete',
    '868 Ochocientos Sesenta Y Ocho',
    '869 Ochocientos Sesenta Y Nueve',
    '870 Ochocientos Setenta',
    '871 Ochocientos Setenta Y Uno',
    '872 Ochocientos Setenta Y Dos',
    '873 Ochocientos Setenta Y Tres',
    '874 Ochocientos Setenta Y Cuatro',
    '875 Ochocientos Setenta Y Cinco',
    '876 Ochocientos Setenta Y Seis',
    '877 Ochocientos Setenta Y Siete',
    '878 Ochocientos Setenta Y Ocho',
    '879 Ochocientos Setenta Y Nueve',
    '880 Ochocientos Ochenta',
    '881 Ochocientos Ochenta Y Uno',
    '882 Ochocientos Ochenta Y Dos',
    '883 Ochocientos Ochenta Y Tres',
    '884 Ochocientos Ochenta Y Cuatro',
    '885 Ochocientos Ochenta Y Cinco',
    '886 Ochocientos Ochenta Y Seis',
    '887 Ochocientos Ochenta Y Siete',
    '888 Ochocientos Ochenta Y Ocho',
    '889 Ochocientos Ochenta Y Nueve',
    '890 Ochocientos Noventa',
    '891 Ochocientos Noventa Y Uno',
    '892 Ochocientos Noventa Y Dos',
    '893 Ochocientos Noventa Y Tres',
    '894 Ochocientos Noventa Y Cuatro',
    '895 Ochocientos Noventa Y Cinco',
    '896 Ochocientos Noventa Y Seis',
    '897 Ochocientos Noventa Y Siete',
    '898 Ochocientos Noventa Y Ocho',
    '899 Ochocientos Noventa Y Nueve',
    '900 Novecientos',
    '901 Novecientos Uno',
    '902 Novecientos Dos',
    '903 Novecientos Tres',
    '904 Novecientos Cuatro',
    '905 Novecientos Cinco',
    '906 Novecientos Seis',
    '907 Novecientos Siete',
    '908 Novecientos Ocho',
    '909 Novecientos Nueve',
    '910 Novecientos Diez',
    '911 Novecientos Once',
    '912 Novecientos Doce',
    '913 Novecientos Trece',
    '914 Novecientos Catorce',
    '915 Novecientos Quince',
    '916 Novecientos Dieciséis',
    '917 Novecientos Diecisiete',
    '918 Novecientos Dieciocho',
    '919 Novecientos Diecinueve',
    '920 Novecientos Veinte',
    '921 Novecientos Veintiuno',
    '922 Novecientos Veintidós',
    '923 Novecientos Veintitrés',
    '924 Novecientos Veinticuatro',
    '925 Novecientos Veinticinco',
    '926 Novecientos Veintiséis',
    '927 Novecientos Veintisiete',
    '928 Novecientos Veintiocho',
    '929 Novecientos Veintinueve',
    '930 Novecientos Treinta',
    '931 Novecientos Treinta Y Uno',
    '932 Novecientos Treinta Y Dos',
    '933 Novecientos Treinta Y Tres',
    '934 Novecientos Treinta Y Cuatro',
    '935 Novecientos Treinta Y Cinco',
    '936 Novecientos Treinta Y Seis',
    '937 Novecientos Treinta Y Siete',
    '938 Novecientos Treinta Y Ocho',
    '939 Novecientos Treinta Y Nueve',
    '940 Novecientos Cuarenta',
    '941 Novecientos Cuarenta Y Uno',
    '942 Novecientos Cuarenta Y Dos',
    '943 Novecientos Cuarenta Y Tres',
    '944 Novecientos Cuarenta Y Cuatro',
    '945 Novecientos Cuarenta Y Cinco',
    '946 Novecientos Cuarenta Y Seis',
    '947 Novecientos Cuarenta Y Siete',
    '948 Novecientos Cuarenta Y Ocho',
    '949 Novecientos Cuarenta Y Nueve',
    '950 Novecientos Cincuenta',
    '951 Novecientos Cincuenta Y Uno',
    '952 Novecientos Cincuenta Y Dos',
    '953 Novecientos Cincuenta Y Tres',
    '954 Novecientos Cincuenta Y Cuatro',
    '955 Novecientos Cincuenta Y Cinco',
    '956 Novecientos Cincuenta Y Seis',
    '957 Novecientos Cincuenta Y Siete',
    '958 Novecientos Cincuenta Y Ocho',
    '959 Novecientos Cincuenta Y Nueve',
    '960 Novecientos Sesenta',
    '961 Novecientos Sesenta Y Uno',
    '962 Novecientos Sesenta Y Dos',
    '963 Novecientos Sesenta Y Tres',
    '964 Novecientos Sesenta Y Cuatro',
    '965 Novecientos Sesenta Y Cinco',
    '966 Novecientos Sesenta Y Seis',
    '967 Novecientos Sesenta Y Siete',
    '968 Novecientos Sesenta Y Ocho',
    '969 Novecientos Sesenta Y Nueve',
    '970 Novecientos Setenta',
    '971 Novecientos Setenta Y Uno',
    '972 Novecientos Setenta Y Dos',
    '973 Novecientos Setenta Y Tres',
    '974 Novecientos Setenta Y Cuatro',
    '975 Novecientos Setenta Y Cinco',
    '976 Novecientos Setenta Y Seis',
    '977 Novecientos Setenta Y Siete',
    '978 Novecientos Setenta Y Ocho',
    '979 Novecientos Setenta Y Nueve',
    '980 Novecientos Ochenta',
    '981 Novecientos Ochenta Y Uno',
    '982 Novecientos Ochenta Y Dos',
    '983 Novecientos Ochenta Y Tres',
    '984 Novecientos Ochenta Y Cuatro',
    '985 Novecientos Ochenta Y Cinco',
    '986 Novecientos Ochenta Y Seis',
    '987 Novecientos Ochenta Y Siete',
    '988 Novecientos Ochenta Y Ocho',
    '989 Novecientos Ochenta Y Nueve',
    '990 Novecientos Noventa',
    '991 Novecientos Noventa Y Uno',
    '992 Novecientos Noventa Y Dos',
    '993 Novecientos Noventa Y Tres',
    '994 Novecientos Noventa Y Cuatro',
    '995 Novecientos Noventa Y Cinco',
    '996 Novecientos Noventa Y Seis',
    '997 Novecientos Noventa Y Siete',
    '998 Novecientos Noventa Y Ocho',
    '999 Novecientos Noventa Y Nueve'
];
 //Convertir numeros a letras

 foreach ($numeros as $key => $value) {
     if (is_numeric($value)) {
        $numero .= $value;
     } else {
        $value=preg_replace('/[0-9]+/', '', $value);
         echo $value."<br>";
     }
 }
?>